services:
    bearo-dev:
        build:
            context: .
            dockerfile: Dockerfile
        image: bearo-dev:latest
        container_name: bearo-dev
        ports:
            - "23791:23791"
        environment:
            - ROCKET_ADDRESS=0.0.0.0
            - ROCKET_PORT=23791
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 512M
                reservations:
                    cpus: "1"
                    memory: 256M
